### ISSUE TITLE
Add StartPage search engine

### ISSUE THREAD

**Issue by Madis0** [Marc-Inc/Peregrine#29]
[StartPage](startpage.com) is a popular search engine, mainly focused as a Google alternative. Please add it to the default list of search engines. 

Example GET URL: `https://www.startpage.com/do/asearch?query={searchTerms}`

**Comment by Marc-Inc** [comment]
Searchengine added, see https://github.com/Marc-Inc/Marc-Inc.github.io/commit/8081fe093b946b00127bb91cdf4a49d3686278b7
